jobs:
  include:
    - stage: deploy
      services:
        - docker
      script:
        - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
            ./deploy.sh;
          fi
