version: "3"

services:
  gateway:
    image: "bombergame/gateway"
    depends_on:
    - auth-service
    - profiles-service
    ports:
    - "${SERVICE_PORT}:80"

  auth-service:
    image: "bombergame/auth-service"
    environment:
    - PROFILES_SERVICE_GRPC_ADDRESS=profiles-service:3000

  profiles-service:
    image: "bombergame/profiles-service"
    depends_on:
    - profiles-storage
    environment:
    - PROFILES_DB_HOST=profiles-storage
    - PROFILES_DB_PORT=5432
    - PROFILES_DB_NAME=${PROFILES_DB_NAME}
    - PROFILES_DB_USER=${PROFILES_DB_USER}
    - PROFILES_DB_PASSWORD=${PROFILES_DB_PASSWORD}

  profiles-storage:
    image: "bombergame/profiles-storage"
    environment:
    - POSTGRES_DB=${PROFILES_DB_NAME}
    - POSTGRES_USER=${PROFILES_DB_USER}
    - POSTGRES_PASSWORD=${PROFILES_DB_PASSWORD}
